export const ALL_PROJECTALL_REQUEST ="ALL_PROJECTALL_REQUEST";
export const ALL_PROJECTALL_SUCCESS ="ALL_PROJECTALL_SUCCESS";
export const ALL_PROJECTALL_FAIL ="ALL_PROJECTALL_FAIL";

export const ADMIN_PROJECTALL_REQUEST ="ADMIN_PROJECTALL_REQUEST";
export const ADMIN_PROJECTALL_SUCCESS ="ADMIN_PROJECTALL_SUCCESS";
export const ADMIN_PROJECTALL_FAIL ="ADMIN_PROJECTALL_FAIL";

export const NEW_PROJECT_REQUEST = "NEW_PROJECT_REQUEST";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PROJECT_RESET ="NEW_PROJECT_RESET";
export const NEW_PROJECT_FAIL = "NEW_PROJECT_FAIL";

export const DELETE_PROJECT_REQUEST ="DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS ="DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_RESET ="DELETE_PROJECT_RESET";
export const DELETE_PROJECT_FAIL ="DELETE_PROJECT_FAIL";


export const PROJECT_DETAILS_REQUEST ="PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS ="PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL ="PROJECT_DETAILS_FAIL";
export const CLEAR_ERRORS ="CLEAR_ERRORS";